import json
import os
import datetime


def generate_lea_notice(
    victim_address,
    suspect_address,
    exchanges_found,
    trace_log,
    stolen_amount_eth=None,
    victim_name='Complainant',
    incident_date=None,
    output_path='LEA_Freeze_Notice.txt'
):
    now = datetime.datetime.now()
    if incident_date is None:
        incident_date = now.strftime('%d-%m-%Y')

    total_eth = stolen_amount_eth or sum(
        e.get('amount_eth', 0) for e in exchanges_found
    )

    lines = []
    lines.append('='*70)
    lines.append('   CYBER CRIME INVESTIGATION UNIT')
    lines.append('   FORMAL FREEZE REQUISITION NOTICE')
    lines.append('   (Under Section 91 CrPC / PMLA 2002 / IT Act 2000)')
    lines.append('='*70)
    lines.append('')
    lines.append('Reference No.  : SIH-CC-' + now.strftime('%Y%m%d%H%M%S'))
    lines.append('Date of Notice : ' + now.strftime('%d %B %Y %H:%M:%S IST'))
    lines.append('Incident Date  : ' + incident_date)
    lines.append('')
    lines.append('-'*70)
    lines.append('COMPLAINANT / VICTIM INFORMATION')
    lines.append('-'*70)
    lines.append('Victim Name           : ' + victim_name)
    lines.append('Victim Wallet Address : ' + victim_address)
    lines.append('Stolen Asset Estimate : {:.6f} ETH'.format(total_eth))
    lines.append('')
    lines.append('-'*70)
    lines.append('SUSPECT INFORMATION')
    lines.append('-'*70)
    lines.append('Suspect Wallet Address: ' + suspect_address)
    lines.append('Blockchain Network    : Ethereum (ERC-20/Native ETH)')
    lines.append('Tracing Method        : Automated Multi-Hop BFS Analytics')
    lines.append('Hops Analyzed         : ' + str(len(trace_log)))
    lines.append('')
    lines.append('-'*70)
    lines.append('IDENTIFIED CRYPTOCURRENCY EXCHANGE DESTINATION(S)')
    lines.append('(Funds Traced to These Off-Ramp Addresses)')
    lines.append('-'*70)

    if exchanges_found:
        for i, ex in enumerate(exchanges_found, 1):
            lines.append('')
            lines.append('  Exchange #{:d}:'.format(i))
            lines.append('    Deposit Address     : ' + str(ex.get('address', 'N/A')))
            lines.append('    Incoming Tx Hash    : ' + str(ex.get('tx_hash', 'N/A')))
            lines.append('    Amount Received     : {:.6f} ETH'.format(ex.get('amount_eth', 0)))
            lines.append('    Detected at Hop     : {:d}'.format(ex.get('hop', 0)))
            lines.append('    ML Confidence Score : {:.2%}'.format(ex.get('exchange_prob', 0)))
    else:
        lines.append('  No direct exchange destinations identified within traced hops.')
        lines.append('  Manual investigation of deeper hops is recommended.')

    lines.append('')
    lines.append('-'*70)
    lines.append('FUND FLOW TRAIL SUMMARY')
    lines.append('-'*70)
    for node in trace_log:
        hop_str = '  Hop {:d} | {:s}...{:s} | {:.4f} ETH | {:s}'.format(
            node.get('hop', 0),
            str(node.get('address', ''))[:10],
            str(node.get('address', ''))[-6:],
            node.get('amount_eth', 0),
            node.get('prediction', 'N/A')
        )
        lines.append(hop_str)

    lines.append('')
    lines.append('-'*70)
    lines.append('ACTION REQUESTED')
    lines.append('-'*70)
    lines.append('')
    lines.append('The Cyber Crime Investigation Unit requests the following')
    lines.append('immediate action from the relevant Cryptocurrency Exchange(s):')
    lines.append('')
    lines.append('  1. FREEZE all assets in the identified deposit wallet address(es).')
    lines.append('  2. PRESERVE all KYC/AML records associated with these accounts.')
    lines.append('  3. SHARE transaction logs and user identification details with')
    lines.append('     the investigating officer under Section 91 CrPC / PMLA 2002.')
    lines.append('  4. HALT any pending withdrawal requests from these addresses.')
    lines.append('')
    lines.append('-'*70)
    lines.append('LEGAL BASIS')
    lines.append('-'*70)
    lines.append('  Section 91 CrPC      : Production of documents & evidence')
    lines.append('  PMLA 2002 Sec. 8     : Attachment and freezing of proceeds of crime')
    lines.append('  IT Act 2000 Sec. 43  : Damage to computer systems / unauthorized access')
    lines.append('  FATF Recommendation 15: Virtual Asset Service Providers (VASPs) compliance')
    lines.append('')
    lines.append('='*70)
    lines.append('  Generated by: SIH Real-Time Crypto Fraud Analytics System')
    lines.append('  Blockchain AI Analysis Engine v1.0')
    lines.append('  Model: Regularized Gradient Boosting + Graph Feature Extraction')
    lines.append('='*70)

    notice_text = '\n'.join(lines)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(notice_text)

    print('[OK] LEA Freeze Notice saved: ' + output_path)
    print('\n' + notice_text)
    return notice_text


def main():
    trace_file = 'trace_result.json'
    if not os.path.exists(trace_file):
        print('[WARN] trace_result.json not found. Running with sample data.')
        exchanges_found = [{
            'address':      '0xabcdef1234567890abcdef1234567890abcdef12',
            'tx_hash':      '0xdeadbeefdeadbeef0000000000000000',
            'amount_eth':   1.5,
            'hop':          2,
            'exchange_prob':0.92,
            'prediction':   'EXCHANGE/HUB IDENTIFIED',
        }]
        trace_log = exchanges_found
        suspect_address = '0x0000000000000000000000000000000000000001'
    else:
        with open(trace_file, 'r') as f:
            data = json.load(f)
        exchanges_found = data.get('identified_exchanges', [])
        trace_log       = data.get('trace_log', [])
        suspect_address = data.get('suspect_address', 'UNKNOWN')

    generate_lea_notice(
        victim_name      = 'Victim / Complainant',
        victim_address   = '0xVICTIM_ADDRESS_HERE',
        suspect_address  = suspect_address,
        exchanges_found  = exchanges_found,
        trace_log        = trace_log,
        output_path      = 'LEA_Freeze_Notice.txt'
    )


if __name__ == '__main__':
    main()
